spring:
  cloud:
    gateway:
      routes:
        # 匹配websocket的路由
        - id: route_websocket
          uri: ws://127.0.0.1:8080
          predicates:
            - Path=/**
          filters:
            - PrefixPath=/ws
            - name: Websocket
