spring:
  cloud:
    gateway:
      routes: 
        - id: route_ws
          uri: http://127.0.0.1:8080
          predicates:
            - Path=/**
          filters:
            - PrefixPath=/ws
            - name: Websocket

config:
  info: version=1
