spring:
  cloud:
    gateway:
      routes: 
        - id: route_cas
          uri: http://127.0.0.1:8088
          predicates:
            - Path=/info
          filters:
            - PrefixPath=/cas
#             - name: Websocket

config:
  info: version=1
